Friendtech
Once-Upon/context pull request #135
Opened 2023-12-15 14:37 UTC by ponyjackal

2023-12-15 18:57 UTC, pcowgill commented on src/protocol/friendTech/constants.ts
> +import FriendTech from './abis/FriendTech';
We should put the chain id it's on in here too

2023-12-15 18:57 UTC, pcowgill commented on src/protocol/friendTech/constants.ts
> +export const FRIEND_TECH_ADDRESSES =
We should put the chain id it's on somewhere in this constants file as well

2023-12-15 18:58 UTC, pcowgill commented on src/protocol/friendTech/friendTech.spec.ts
> +    expect(desc1).toBe('YOUR_DESCRIPTION_HERE');
TODO: Change before merging

2023-12-15 18:59 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +// Contextualize for mined txs
```suggestion
// Contextualize for txs
```
We shouldn't keep using "mined" in these comments. It makes less sense with proof of stake

2023-12-15 18:59 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +        parsedLog.args.trader === parsedLog.args.subject &&
@ponyjackal There's a type error here

2023-12-15 19:01 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +            default: '[[trader]] [[soldShares]] from [[subject]] for [[price]]',
```suggestion
            default: '[[trader]] [[soldShares]] of [[subject]] for [[price]]',
```

2023-12-15 19:01 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +              '[[buyer]] [[boughtShares]] from [[subject]] for [[price]]',
```suggestion
              '[[buyer]] [[boughtShares]] of [[subject]] for [[price]]',
```

2023-12-15 19:01 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +                '[[buyer]] [[boughtShares]] from [[subject]] for [[price]]',
```suggestion
                '[[buyer]] [[boughtShares]] of [[subject]] for [[price]]',
```

2023-12-18 16:53 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +            value: 'BOUGHT_SHARES',
Yes, they did. Let's call these keys @ponyjackal

2023-12-18 16:53 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +            value: 'BOUGHT_SHARES',
```suggestion
            value: 'BOUGHT_KEYS',
```

2023-12-18 16:54 UTC, pcowgill commented on src/protocol/friendTech/friendTech.spec.ts
> +      '0x306dd2B26F1383c62925F58151263D9E5656E86E BOUGHT_SHARES of 0xD6820270E904A5E4527d765afF9534f07E55d2BD for 0.004 ETH',
```suggestion
      '0x306dd2B26F1383c62925F58151263D9E5656E86E BOUGHT_KEYS of 0xD6820270E904A5E4527d765afF9534f07E55d2BD for 0.004 ETH',
```

2023-12-18 16:54 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +          failedToBuyShares: {
```suggestion
          failedToBuyKeys: {
```

2023-12-18 16:54 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +            value: 'FAILED_TO_BUY_SHARES',
```suggestion
            value: 'FAILED_TO_BUY_KEYS',
```

2023-12-18 16:54 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +              '[[buyer]] [[failedToBuyShares]] of [[subject]] for [[price]]',
```suggestion
              '[[buyer]] [[failedToBuyKeys]] of [[subject]] for [[price]]',
```

2023-12-18 16:55 UTC, pcowgill commented on src/types/contextAction/protocolContextAction.ts
> +  | 'FAILED_TO_BUY_SHARES'
```suggestion
  | 'FAILED_TO_BUY_KEYS'
```

2023-12-18 16:55 UTC, pcowgill commented on src/types/contextAction/protocolContextAction.ts
> +  | 'BOUGHT_SHARES'
```suggestion
  | 'BOUGHT_KEYS'
```

2023-12-18 16:55 UTC, pcowgill commented on src/types/contextAction/protocolContextAction.ts
> +  | 'SOLD_SHARES';
```suggestion
  | 'SOLD_KEYS';
```

2023-12-18 16:56 UTC, pcowgill commented on src/protocol/friendTech/constants.ts
> +export const CHAIN_ID = 1;
```suggestion
export const CHAIN_ID = 8453;
```

2023-12-18 16:57 UTC, pcowgill commented on src/protocol/friendTech/constants.ts
> +export const ABIs = {
@ponyjackal Should we do any `as const` in here to get the types with the abi working?

2023-12-18 16:58 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +    if (transaction.sigHash === '0x6945b123') {
@ponyjackal Extract this into a const to share it with the detect logic

2023-12-18 16:58 UTC, pcowgill commented on src/protocol/friendTech/constants.ts
> +export const ABIs = {
Never mind, it looks like it's already working without the as Abi downcast

2023-12-18 17:00 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +            title: 'Friendtech',
```suggestion
            title: 'friend.tech',
```

2023-12-18 17:00 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +              title: 'Friendtech',
```suggestion
              title: 'friend.tech',
```

2023-12-18 17:00 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +            title: 'Friendtech',
```suggestion
            title: 'friend.tech',
```

2023-12-18 17:01 UTC, pcowgill requested changes
@ponyjackal Looking good! I requested a few small changes

2023-12-18 17:01 UTC, pcowgill commented on src/protocol/friendTech/abis/FriendTech.ts
> +    name: 'buyShares',
@ponyjackal We'll have to keep the naming as shares here, since that's what it's called in the contracts

2023-12-21 00:19 UTC, pcowgill requested changes
Looking good! I requested a few blocking changes.

2023-12-21 00:19 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +                '[[buyer]] [[boughtShares]] of [[subject]] for [[price]]',
We should use a shorter sentence in this case - we don't have all these variables. Maybe "[[subject]] SIGNED_UP"

2023-12-21 00:19 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +            default: '[[buyer]] [[boughtKeys]] of [[subject]] for [[price]]',
I realized we should include the number of keys they bought in order for the price to be relevant

2023-12-21 00:19 UTC, pcowgill commented on src/protocol/friendTech/friendTech.ts
> +            default: '[[trader]] [[soldKeys]] of [[subject]] for [[price]]',
Include number of keys for selling as well

2023-12-21 00:19 UTC, pcowgill commented on src/protocol/friendTech/friendTech.spec.ts
> +  it('Should generate FriendTech context', () => {
Let's include tests for selling, for failing to buy, and for signing up

2023-12-21 00:19 UTC, pcowgill commented on src/types/contextAction/protocolContextAction.ts
> +  | 'SOLD_KEYS';
We should include SIGNED_UP as well

2023-12-21 00:35 UTC, ponyjackal commented on src/protocol/friendTech/friendTech.ts
> +                '[[buyer]] [[boughtShares]] of [[subject]] for [[price]]',
@pcowgill would you please describe the default description in this case?

2023-12-21 17:36 UTC, pcowgill approved these changes

2023-12-21 17:36 UTC, merged