NFT mint contextualization default should show the number of
Once-Upon/context pull request #136
Opened 2023-12-15 16:20 UTC by ponyjackal

2023-12-18 16:37 UTC, pcowgill commented on src/heuristics/erc1155Mint/erc1155Mint.spec.ts
> +      '0x74b78e98093f5b522a7ebdac3b994641ca7c2b20 MINTED 0xf4dd946d1406e215a87029db56c69e1bcf3e1773 #1 for 0 ETH',
@ponyjackal I think #1 doesn't make sense for ERC1155, they aren't numbered in order like with ERC721
```suggestion
      '0x74b78e98093f5b522a7ebdac3b994641ca7c2b20 MINTED 1 0xf4dd946d1406e215a87029db56c69e1bcf3e1773 for 0 ETH',
```

2023-12-18 16:38 UTC, pcowgill commented on src/heuristics/erc1155Mint/erc1155Mint.ts
> +    transaction.netAssetTransfers === undefined // TODO: This is a hack because of an issue with netAssetTransfers transformer
Why this syntax rather than `!transaction.netAssetTransfers`?

2023-12-18 16:39 UTC, pcowgill commented on src/heuristics/erc1155Mint/erc1155Mint.ts
> +      !WETH_ADDRESSES.includes(transfer.asset),
@ponyjackal Specifically checking for WETH only matters for ERC20, not for ERC1155, right?

2023-12-18 16:40 UTC, pcowgill commented on src/heuristics/erc1155Mint/erc1155Mint.ts
> +      !WETH_ADDRESSES.includes(transfer.asset),
If we move the erc1155 check up, that is

2023-12-18 16:50 UTC, pcowgill commented on src/heuristics/erc1155Mint/erc1155Mint.ts
> +        title: 'Token Mint',
```suggestion
        title: 'NFT Mint',
```

2023-12-18 16:51 UTC, pcowgill commented on src/heuristics/erc20Mint/erc20Mint.ts
>          title: 'Token Mint',
```suggestion
        title: 'ERC20 Mint',
```

2023-12-18 16:52 UTC, pcowgill commented on src/heuristics/erc721Mint/erc721Mint.ts
> +      !WETH_ADDRESSES.includes(transfer.asset),
@ponyjackal Same comment about WETH check not being needed for a non-ERC20 contextualizer

2023-12-18 16:52 UTC, pcowgill commented on src/heuristics/erc721Mint/erc721Mint.ts
> +        title: 'Token Mint',
```suggestion
        title: 'NFT Mint',
```

2023-12-18 16:52 UTC, pcowgill requested changes
@ponyjackal This is looking great! I requested a few small changes.

2023-12-18 17:36 UTC, ponyjackal commented on src/heuristics/erc1155Mint/erc1155Mint.spec.ts
> +      '0x74b78e98093f5b522a7ebdac3b994641ca7c2b20 MINTED 0xf4dd946d1406e215a87029db56c69e1bcf3e1773 #1 for 0 ETH',
@pcowgill FYI, this is from current FE, I think it should be updated as well

2023-12-18 17:38 UTC, ponyjackal commented on src/heuristics/erc1155Mint/erc1155Mint.ts
> +    transaction.netAssetTransfers === undefined // TODO: This is a hack because of an issue with netAssetTransfers transformer
Its relying on both assetTransfers, and netAssetTransfers

2023-12-18 22:15 UTC, pcowgill commented on src/heuristics/erc1155Mint/erc1155Mint.spec.ts
> +      '0x74b78e98093f5b522a7ebdac3b994641ca7c2b20 MINTED 0xf4dd946d1406e215a87029db56c69e1bcf3e1773 #1 for 0 ETH',
I created a Linear issue for that https://linear.app/onceupon/issue/OU-1423/for-erc1155s-show-5-[[contractaddress]-rather-than-[contractaddress]-5

2023-12-18 22:15 UTC, pcowgill commented on src/heuristics/erc1155Mint/erc1155Mint.ts
> +    transaction.netAssetTransfers === undefined // TODO: This is a hack because of an issue with netAssetTransfers transformer
Sorry, that wasn't my question. I'm asking specifically about line 22, could that use a `!` instead of comparing with `undefined`?

2023-12-18 22:17 UTC, pcowgill commented on src/heuristics/erc1155Mint/erc1155Mint.spec.ts
> +      '0x74b78e98093f5b522a7ebdac3b994641ca7c2b20 MINTED 1 0xf4dd946d1406e215a87029db56c69e1bcf3e1773 #1 for 0 ETH',
```suggestion
      '0x74b78e98093f5b522a7ebdac3b994641ca7c2b20 MINTED 1 0xf4dd946d1406e215a87029db56c69e1bcf3e1773 for 0 ETH',
```

2023-12-19 00:03 UTC, ponyjackal commented on src/heuristics/erc1155Mint/erc1155Mint.spec.ts
> +      '0x74b78e98093f5b522a7ebdac3b994641ca7c2b20 MINTED 1 0xf4dd946d1406e215a87029db56c69e1bcf3e1773 #1 for 0 ETH',
@pcowgill I am not sure if we don't need `tokenId` for ERC1155 tokens?

2023-12-19 01:50 UTC, pcowgill commented on src/heuristics/erc1155Mint/erc1155Mint.spec.ts
> +      '0x74b78e98093f5b522a7ebdac3b994641ca7c2b20 MINTED 1 0xf4dd946d1406e215a87029db56c69e1bcf3e1773 for 0 ETH',
@ponyjackal We'll need to change the `ERC1155Mint.ts` file to match this expected behavior

2023-12-19 02:21 UTC, pcowgill approved these changes

2023-12-19 02:24 UTC, merged