Missing value for erc20 mint
Once-Upon/context pull request #145
Opened 2023-12-19 13:32 UTC by ponyjackal

2023-12-19 17:30 UTC, pcowgill requested changes

2023-12-19 17:30 UTC, pcowgill commented on src/heuristics/erc1155Mint/erc1155Mint.ts
> +  if (price && Number(price) > 0) {
We should include price even when it's 0

2023-12-19 17:51 UTC, pcowgill commented on src/heuristics/erc1155Mint/erc1155Mint.ts
> +      '[[recipient]] [[minted]] [[amount]] [[token]]';
@ponyjackal We need to undo this change, right?

2023-12-19 17:52 UTC, pcowgill commented on src/heuristics/erc20Mint/erc20Mint.ts
> +  const price = assetSent[0]?.value ?? '0';
@ponyjackal Previously, was it omitting the `value` key for `variables.price` when this wasn't set to '0'?

2023-12-19 17:53 UTC, ponyjackal commented on src/heuristics/erc20Mint/erc20Mint.ts
> +  const price = assetSent[0]?.value ?? '0';
Yes

2023-12-20 02:16 UTC, pcowgill approved these changes

2023-12-20 02:16 UTC, merged