Benguyen0214/ou 1962 contextualize uniswap swap using this event for detection
Once-Upon/context pull request #280
Opened 2024-04-03 17:52 UTC by ponyjackal

2024-04-03 18:00 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV2/uniswapV2Pair.ts
> +  const isEnjoy = detect(transaction);
```suggestion
  const isUniswapV2Pair = detect(transaction);
```

2024-04-03 18:01 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV2/uniswapV2Pair.ts
> +  if (!isEnjoy) return transaction;
```suggestion
  if (!isUniswapV2Pair) return transaction;
```

2024-04-03 18:02 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV2/constants.ts
> +  '0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822';
@ponyjackal We don't use this pattern anymore, we use viem with the event signature in plain text

2024-04-03 18:02 UTC, pcowgill requested changes
https://github.com/Once-Upon/context/pull/280/files#r1550224811

2024-04-03 18:04 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV2/uniswapV2Pair.ts
> +        default: '[[lp]][[contextAction]]with[[numETH]]and[[numENJOY]]',
```suggestion
        default: '[[sender]][[contextAction]]with[[numETH]]and[[numENJOY]]',
```

2024-04-03 18:05 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV2/uniswapV2Pair.ts
> +      numENJOY: {
```suggestion
      erc20Token2: {
```

2024-04-03 18:05 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV2/uniswapV2Pair.ts
> +      numETH: {
```suggestion
      erc20Token1: {
```

2024-04-03 18:08 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV3/README.md
> +### Uniswap V2 contract
```suggestion
### Uniswap V3 contract
```

2024-04-03 18:08 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV3/README.md
> +| Enjoy    | [0xa6b280b42cb0b7c4a4f789ec6ccc3a7609a1bc39](https://www.onceupon.gg/0xa6b280b42cb0b7c4a4f789ec6ccc3a7609a1bc39:7777777) | 7777777  |
@ponyjackal Is the Enjoy token using Uniswap V3 or V2?

2024-04-03 18:09 UTC, pcowgill commented
@ponyjackal We should update the Uniswap V2 README to include a contract with a pair tx, either a particular pool pair or the router contract with a filter applied.

2024-04-03 18:10 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV3/constants.ts
> +  '0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67';
@ponyjackal Let's change this to use the viem approach with the Swap(...args) event itself

2024-04-03 18:10 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV3/uniswapV3Pair.spec.ts
> +      '0xcb1355ff08ab38bbce60111f1bb2b784be25d7e8 swapped 1412595572402230 0x4200000000000000000000000000000000000006 for 1372743836828975471 0x4200000000000000000000000000000000000042',
This test case looks good

2024-04-03 18:11 UTC, pcowgill commented on src/types/contextAction/protocolContextAction.ts
> +export type UniswapV2RouterAction = 'ADDED_LIQUIDITY' | 'SWAP';
```suggestion
export type UniswapV2RouterAction = 'ADDED_LIQUIDITY';
```

2024-04-03 18:12 UTC, pcowgill commented on src/types/contextAction/protocolContextAction.ts
> +export type UniswapV2RouterAction = 'ADDED_LIQUIDITY' | 'SWAP';
@ponyjackal If we were to include this here, it should be in past tense, `SWAPPED`. However, I think it makes sense in this case to reuse the heuristic context action of `SWAPPED` rather than adding a new one here.

2024-04-03 18:27 UTC, ponyjackal commented on src/contextualizers/protocol/uniswapV3/README.md
> +| Enjoy    | [0xa6b280b42cb0b7c4a4f789ec6ccc3a7609a1bc39](https://www.onceupon.gg/0xa6b280b42cb0b7c4a4f789ec6ccc3a7609a1bc39:7777777) | 7777777  |
v2

2024-04-04 18:04 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV2/constants.ts
> +  '0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822';
@ponyjackal Let's make this change before merging this

2024-04-04 18:05 UTC, pcowgill requested changes
https://github.com/Once-Upon/context/pull/280/files#r1552194455

2024-04-04 18:06 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV2/README.md
> +| V2Router | [0xa00f34a632630efd15223b1968358ba4845beec7](https://www.onceupon.gg/0xa00f34a632630efd15223b1968358ba4845beec7:7777777) | 7777777  |
```suggestion
| V2Router on Zora | [0xa00f34a632630efd15223b1968358ba4845beec7](https://www.onceupon.gg/0xa00f34a632630efd15223b1968358ba4845beec7:7777777) | 7777777  |
```

2024-04-05 16:17 UTC, ponyjackal commented on src/contextualizers/protocol/uniswapV2/constants.ts
> +  '0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822';
@pcowgill Above hash is not used, I removed

2024-04-05 16:33 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV3/constants.ts
> +  '0xa6b280b42cb0b7c4a4f789ec6ccc3a7609a1bc39';
```suggestion
```

2024-04-05 16:34 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV3/index.ts
> +export const uniswapV2Contextualizer = {
```suggestion
export const uniswapV3Contextualizer = {
```

2024-04-05 16:39 UTC, pcowgill commented on src/contextualizers/protocol/uniswapV3/uniswapV3Pair.ts
> +    if (decoded && decoded.eventName === 'Swap') return true;
@ponyjackal Can we assert on argument names too here?

2024-04-05 16:39 UTC, pcowgill approved these changes

2024-04-05 16:42 UTC, merged