Token airdrop
Once-Upon/context pull request #38
Opened 2023-12-01 17:16 UTC by ponyjackal

2023-12-01 22:41 UTC, pcowgill commented on src/heuristics/tokenAirdrop.ts
> +    const received = transaction.netAssetTransfers[address].received;
```suggestion
    const sent = transaction.netAssetTransfers[address]?.sent;
    const received = transaction.netAssetTransfers[address]?.received;
```

2023-12-01 22:42 UTC, pcowgill commented on src/heuristics/tokenAirdrop.ts
> +    if (sent.length > 0 || received.length === 0) {
```suggestion
    if (sent && sent.length > 0 || received && received.length === 0) {
```

2023-12-01 22:42 UTC, pcowgill commented on src/heuristics/tokenAirdrop.ts
> +    if (sent.length > 0 || received.length === 0) {
Otherwise it might throw an error when checking the length

2023-12-01 22:42 UTC, pcowgill requested changes
@ponyjackal I added some suggestions we should include before merging this.

2023-12-02 14:37 UTC, jordanmessina approved these changes
Paul's suggestions are great.

2023-12-04 12:45 UTC, ponyjackal commented on src/heuristics/tokenAirdrop.ts
> +    const received = transaction.netAssetTransfers[address].received;
![image](https://github.com/Once-Upon/context/assets/47555611/1329b11f-98cb-4b71-b763-1ca9aed3bd71)

Since I am iterating the key values in the object, the above optional chainings are pointless, I think

2023-12-05 02:43 UTC, pcowgill approved these changes

2023-12-05 02:43 UTC, merged

2023-12-05 02:44 UTC, pcowgill commented
The `npm run run:contextualizers` script had a passing result
<img width="882" alt="Screenshot 2023-12-04 at 8 43 51 PM" src="https://github.com/Once-Upon/context/assets/2731712/b0942dca-4041-49ec-b757-41f388cb6450">