Update context action objects
Once-Upon/context pull request #387
Opened 2024-06-18 15:34 UTC by guscost

2024-06-18 15:35 UTC, guscost commented on src/contextualizers/heuristics/erc20Mint/erc20Mint.ts
> +        value: HeuristicContextActionEnum.MINTED.split(".").pop() || "",
This does nothing for heuristic (non-prefixed) actions, but is left here as an example of how the value would be calculated.

2024-06-18 15:42 UTC, pcowgill commented on src/contextualizers/heuristics/erc20Mint/erc20Mint.ts
> +        value: HeuristicContextActionEnum.MINTED.split(".").pop() || "",
I was assuming that as a rule no enums would contain a . If we ever want the string containing a ".", we compute that from the enum and the protocol name

2024-06-18 15:43 UTC, pcowgill commented on src/contextualizers/heuristics/erc20Mint/erc20Mint.ts
> +        value: HeuristicContextActionEnum.MINTED.split(".").pop() || "",
That would mean that for id and for `actions` above, we add the "." and the protocol name

2024-06-18 15:44 UTC, pcowgill commented on src/contextualizers/heuristics/erc20Mint/erc20Mint.ts
> +        value: HeuristicContextActionEnum.MINTED.split(".").pop() || "",
Maybe we can make the change in a protocol contextualizer to show how it behaves in the case where there is a protocol name too

2024-06-18 16:18 UTC, guscost commented on src/contextualizers/heuristics/erc20Mint/erc20Mint.ts
> +        value: HeuristicContextActionEnum.MINTED.split(".").pop() || "",
I guess that makes sense, fewer type changes too. OK will try that way, 1sec

2024-06-18 16:59 UTC, pcowgill commented on src/contextualizers/protocol/basepaint/basepaint.ts
> +            id: `${Protocols.BASEPAINT}.${BasepaintActionEnum.PAINTED}`,
@guscost I think `summaries.en.title` should be `Protocols.BASEPAINT` too

2024-06-18 16:59 UTC, pcowgill commented on src/types/context.ts
> +  id:
Nice!

2024-06-19 13:58 UTC, pcowgill requested changes
We'll need to add the `actions` array at the same level as variables and summaries for each contextualization in this PR too

2024-06-19 13:59 UTC, pcowgill commented on src/contextualizers/heuristics/erc20Mint/erc20Mint.ts
> +    actions: [HeuristicContextActionEnum.MINTED],
We have actions here, so the remaining work is to propagate this change to other contextualizers

2024-06-19 14:00 UTC, pcowgill commented on src/contextualizers/protocol/basepaint/basepaint.ts
> +            title: ProtocolMap[Protocols.BASEPAINT],
This approach is nice

2024-06-19 14:04 UTC, pcowgill commented on src/types/contextAction/index.ts
> +export type ContextActionFull =
Maybe `ContextActionID` would be a more consistent name with the way we use id within variables of type `contextAction`
```suggestion
export type ContextActionID =
```

2024-06-19 14:04 UTC, pcowgill reviewed
Other than the requested changes, I reviewed the rest of the PR, and it looks great!

2024-06-20 17:07 UTC, guscost commented on src/contextualizers/heuristics/erc20Mint/erc20Mint.ts
> +    actions: [HeuristicContextActionEnum.MINTED],
Done!

2024-06-20 20:56 UTC, pcowgill commented on src/contextualizers/bridges/acrossProtocol/source.ts
> +
@guscost This newline isn't ideal, but doesn't matter

2024-06-20 21:04 UTC, merged