Key changes to gold function calls and events
Once-Upon/context pull request #395
Opened 2024-07-01 17:43 UTC by ponyjackal

Resolve OU-2666
Resolve OU-2667

2024-07-01 20:13 UTC, pcowgill commented
@ponyjackal Could you take a look at the build failure?

2024-07-01 20:33 UTC, pcowgill commented on src/contextualizers/protocol/index.ts
> +import { goldContextualizer } from './cropXYZ';
```suggestion
import { cropXyzContextualizer } from './cropXYZ';
```

2024-07-01 20:34 UTC, pcowgill commented on src/types/contextAction/protocolContextAction.ts
>  export enum GoldContextActionEnum {
```suggestion
export enum CropXyzContextActionEnum {
```

2024-07-01 20:34 UTC, pcowgill commented on src/types/contextAction/protocolContextAction.ts
>  export type GoldContextAction =
```suggestion
export type CropXyzContextAction =
```

2024-07-01 20:35 UTC, pcowgill commented on src/contextualizers/protocol/cropXYZ/source.spec.ts
> +describe('Gold Source', () => {
```suggestion
describe('CropXYZ Source', () => {
```

2024-07-01 20:35 UTC, pcowgill commented on src/contextualizers/protocol/cropXYZ/source.spec.ts
> +    expect(transaction1.context?.summaries?.en.title).toBe('Gold');
```suggestion
    expect(transaction1.context?.summaries?.en.title).toBe('CropXYZ');
```

2024-07-01 20:35 UTC, pcowgill commented on src/contextualizers/protocol/cropXYZ/source.spec.ts
> +    const isGoldSource1 = detect(
```suggestion
    const isCropXyzSource1 = detect(
```

2024-07-01 20:36 UTC, pcowgill commented on src/contextualizers/protocol/cropXYZ/plotAction.ts
> +            title: `Gold`,
```suggestion
            title: `CropXYZ`,
```

2024-07-01 20:37 UTC, pcowgill commented on src/contextualizers/protocol/cropXYZ/plotAction.ts
> +            default: '[[player]][[clearedHarvest]]plots[[plotId]]',
We'll keep this like this for now, but an open question is whether we want to render the player given their non-trivial use of account abstraction, etc.

2024-07-01 20:39 UTC, pcowgill commented on src/contextualizers/protocol/cropXYZ/destination.ts
> +    // || gameMintedTokenDecoded.length !== 2
@ponyjackal What's the context on why this is commented out?

2024-07-01 20:40 UTC, pcowgill commented on src/contextualizers/protocol/cropXYZ/plotAction.spec.ts
> +      '0x9a37e57d177c5ff8817b55da36f2a2b3532cde3f ACTIVATED_A_STARTER_PACK',
@ponyjackal We'll change this to be a different action, right?

2024-07-01 20:41 UTC, pcowgill commented on src/contextualizers/protocol/cropXYZ/plotAction.ts
> +            default: '[[player]][[harvested]]plots[[plotId]]',
@ponyjackal We should use net asset transfers to detect the amount of tokens that moved to add to this

2024-07-01 20:42 UTC, pcowgill requested changes
Heading in the right direction! I requested a few changes in the comments.

2024-07-01 21:06 UTC, pcowgill commented on src/contextualizers/protocol/cropXYZ/plotAction.ts
> +            default: '[[player]][[harvested]]plots[[plotId]]',
We can use the asset transfer helper in this repo to include this info

2024-07-02 00:05 UTC, ponyjackal commented on src/contextualizers/protocol/cropXYZ/destination.ts
> +    // || gameMintedTokenDecoded.length !== 2
@pcowgill I cant not recall this correctly, but for the current contract, there is no event emitted for GameTokenMinted

2024-07-02 00:06 UTC, ponyjackal commented on src/contextualizers/protocol/cropXYZ/plotAction.spec.ts
> +      '0x9a37e57d177c5ff8817b55da36f2a2b3532cde3f ACTIVATED_A_STARTER_PACK',
Yeah, this test is not working, I tried to grab the only transaction in plotAction contract tx history, but it didnt work

2024-07-02 00:37 UTC, pcowgill commented on src/contextualizers/protocol/cropXYZ/plotAction.spec.ts
> +      '0x9a37e57d177c5ff8817b55da36f2a2b3532cde3f ACTIVATED_A_STARTER_PACK',
Ah ok, but with the tx links I sent over in the Linear issue, you have txs you can use now, right?

2024-07-02 00:39 UTC, ponyjackal commented on src/contextualizers/protocol/cropXYZ/plotAction.spec.ts
> +      '0x9a37e57d177c5ff8817b55da36f2a2b3532cde3f ACTIVATED_A_STARTER_PACK',
Yeah

2024-07-02 14:44 UTC, pcowgill commented on src/contextualizers/protocol/cropXyz/plotAction.spec.ts
> +    //   '0x402533d5240A0c51e02d3714C0D0A057384D4872 HARVESTED_PLOT 257 0x9c82ca3332898bea9c9fa5f9642ba4a4628e1321',
```suggestion
    //   '0x402533d5240A0c51e02d3714C0D0A057384D4872 CLEARED_HARVEST for plot 257',
```

2024-07-02 15:24 UTC, pcowgill approved these changes

2024-07-02 15:24 UTC, merged